build:
  environment:
    php:
      version: 5.5
  tests:
    override:
      -
        command: 'phpunit --coverage-clover=clover.xml'
        coverage:
          file: 'clover.xml'
          format: 'clover'